version: '3.8'
services:
  java-maven-app:
    image: kelz107/nana-projects:3.0
    ports:
      - 8080:80
    
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=my-pwd